---

# Copy the cli binaries to Nginx directory

- local_action: stat path={{ openwhisk_cli.local.location }}/{{ item }}
  register: binary_path

- name: "copy the local binaries from a local directory to Nginx directory"
  copy: src={{ openwhisk_cli.local.location }}/{{ item }} dest={{ cli.nginxdir }}/
  when: binary_path.stat.exists
